# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuestionUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(892, 827)
        Dialog.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 255);"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 871, 121))
        self.groupBox_4.setStyleSheet(_fromUtf8(""))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(360, 0, 61, 41))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 171, 41))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_subject = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_subject.setGeometry(QtCore.QRect(140, 10, 191, 22))
        self.comboBox_subject.setObjectName(_fromUtf8("comboBox_subject"))
        self.comboBox_Year = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_Year.setGeometry(QtCore.QRect(470, 10, 121, 22))
        self.comboBox_Year.setObjectName(_fromUtf8("comboBox_Year"))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(360, 40, 61, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox_Semester = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_Semester.setGeometry(QtCore.QRect(470, 50, 121, 22))
        self.comboBox_Semester.setObjectName(_fromUtf8("comboBox_Semester"))
        self.comboBox_Semester.addItem(_fromUtf8(""))
        self.comboBox_Semester.addItem(_fromUtf8(""))
        self.comboBox_Semester.addItem(_fromUtf8(""))
        self.comboBox_papertype = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_papertype.setGeometry(QtCore.QRect(140, 50, 191, 22))
        self.comboBox_papertype.setObjectName(_fromUtf8("comboBox_papertype"))
        self.comboBox_papertype.addItem(_fromUtf8(""))
        self.comboBox_papertype.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 171, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(620, 0, 61, 41))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_TotalMarks = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_TotalMarks.setGeometry(QtCore.QRect(190, 80, 141, 31))
        self.lineEdit_TotalMarks.setInputMask(_fromUtf8(""))
        self.lineEdit_TotalMarks.setObjectName(_fromUtf8("lineEdit_TotalMarks"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(18, 79, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_RemainMarks = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_RemainMarks.setGeometry(QtCore.QRect(450, 80, 141, 31))
        self.lineEdit_RemainMarks.setInputMask(_fromUtf8(""))
        self.lineEdit_RemainMarks.setObjectName(_fromUtf8("lineEdit_RemainMarks"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(358, 79, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(618, 79, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_Papermarks = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Papermarks.setGeometry(QtCore.QRect(710, 80, 141, 31))
        self.lineEdit_Papermarks.setInputMask(_fromUtf8(""))
        self.lineEdit_Papermarks.setObjectName(_fromUtf8("lineEdit_Papermarks"))
        self.comboBox_date = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_date.setGeometry(QtCore.QRect(700, 10, 151, 22))
        self.comboBox_date.setObjectName(_fromUtf8("comboBox_date"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(620, 40, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_Paperno = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Paperno.setGeometry(QtCore.QRect(710, 40, 141, 31))
        self.lineEdit_Paperno.setInputMask(_fromUtf8(""))
        self.lineEdit_Paperno.setObjectName(_fromUtf8("lineEdit_Paperno"))
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 450, 871, 291))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(40)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 871, 221))
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(660, 120, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_Search = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Search.setGeometry(QtCore.QRect(95, 170, 171, 31))
        self.lineEdit_Search.setInputMask(_fromUtf8(""))
        self.lineEdit_Search.setObjectName(_fromUtf8("lineEdit_Search"))
        self.spinBox_Questionmarks = QtGui.QSpinBox(self.groupBox)
        self.spinBox_Questionmarks.setGeometry(QtCore.QRect(780, 130, 71, 22))
        self.spinBox_Questionmarks.setObjectName(_fromUtf8("spinBox_Questionmarks"))
        self.pushButton_Add = QtGui.QPushButton(self.groupBox)
        self.pushButton_Add.setGeometry(QtCore.QRect(760, 170, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Add.setFont(font)
        self.pushButton_Add.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        self.pushButton_Add.setObjectName(_fromUtf8("pushButton_Add"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(15, 30, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.textEdit_Question = QtGui.QTextEdit(self.groupBox)
        self.textEdit_Question.setGeometry(QtCore.QRect(100, 10, 751, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.textEdit_Question.setFont(font)
        self.textEdit_Question.setObjectName(_fromUtf8("textEdit_Question"))
        self.pushButton_Update = QtGui.QPushButton(self.groupBox)
        self.pushButton_Update.setGeometry(QtCore.QRect(395, 170, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Update.setFont(font)
        self.pushButton_Update.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        self.pushButton_Update.setObjectName(_fromUtf8("pushButton_Update"))
        self.pushButton_Delete = QtGui.QPushButton(self.groupBox)
        self.pushButton_Delete.setGeometry(QtCore.QRect(285, 170, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Delete.setFont(font)
        self.pushButton_Delete.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        self.pushButton_Delete.setObjectName(_fromUtf8("pushButton_Delete"))
        self.pushButton_Insert = QtGui.QPushButton(self.groupBox)
        self.pushButton_Insert.setGeometry(QtCore.QRect(640, 170, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Insert.setFont(font)
        self.pushButton_Insert.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        self.pushButton_Insert.setObjectName(_fromUtf8("pushButton_Insert"))
        self.pushButton_Cancel = QtGui.QPushButton(self.groupBox)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(515, 170, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        self.pushButton_Cancel.setObjectName(_fromUtf8("pushButton_Cancel"))
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(20, 170, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 871, 71))
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, -10, 851, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8(""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_filelocation = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_filelocation.setGeometry(QtCore.QRect(130, 31, 341, 31))
        self.lineEdit_filelocation.setInputMask(_fromUtf8(""))
        self.lineEdit_filelocation.setObjectName(_fromUtf8("lineEdit_filelocation"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(8, 30, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.pushButton_browse = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_browse.setGeometry(QtCore.QRect(500, 30, 93, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.pushButton_extract = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_extract.setGeometry(QtCore.QRect(750, 10, 101, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_extract.setFont(font)
        self.pushButton_extract.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 127);"))
        self.pushButton_extract.setObjectName(_fromUtf8("pushButton_extract"))
        self.pushButton_Generate = QtGui.QPushButton(Dialog)
        self.pushButton_Generate.setGeometry(QtCore.QRect(750, 760, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Generate.setFont(font)
        self.pushButton_Generate.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ICONS/settings2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Generate.setIcon(icon)
        self.pushButton_Generate.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Generate.setObjectName(_fromUtf8("pushButton_Generate"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Questions", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Year</p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>Subject Code</p></body></html>", None))
        self.comboBox_Year.setItemText(0, _translate("Dialog", "2015", None))
        self.comboBox_Year.setItemText(1, _translate("Dialog", "2016", None))
        self.comboBox_Year.setItemText(2, _translate("Dialog", "2017", None))
        self.comboBox_Year.setItemText(3, _translate("Dialog", "2018", None))
        self.comboBox_Year.setItemText(4, _translate("Dialog", "2019", None))
        self.comboBox_Year.setItemText(5, _translate("Dialog", "2020", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>Semester</p></body></html>", None))
        self.comboBox_Semester.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox_Semester.setItemText(1, _translate("Dialog", "2", None))
        self.comboBox_Semester.setItemText(2, _translate("Dialog", "3", None))
        self.comboBox_papertype.setItemText(0, _translate("Dialog", "Final Exam", None))
        self.comboBox_papertype.setItemText(1, _translate("Dialog", "Mid Semester", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>Question Type</p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>Date</p></body></html>", None))
        self.lineEdit_TotalMarks.setPlaceholderText(_translate("Dialog", "Enter Total Marks", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>Total Marks</p></body></html>", None))
        self.lineEdit_RemainMarks.setPlaceholderText(_translate("Dialog", "Question No", None))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>Question No</p></body></html>", None))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>Paper Marks</p></body></html>", None))
        self.lineEdit_Papermarks.setPlaceholderText(_translate("Dialog", "Paper Marks", None))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>Paper No</p></body></html>", None))
        self.lineEdit_Paperno.setPlaceholderText(_translate("Dialog", "Paper No", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "No", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Process", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Marks", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Question", None))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p>Question Marks</p></body></html>", None))
        self.lineEdit_Search.setPlaceholderText(_translate("Dialog", "Enter Question", None))
        self.pushButton_Add.setText(_translate("Dialog", "Add", None))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p>Question</p></body></html>", None))
        self.pushButton_Update.setText(_translate("Dialog", "Update", None))
        self.pushButton_Delete.setText(_translate("Dialog", "Delete", None))
        self.pushButton_Insert.setText(_translate("Dialog", "Insert", None))
        self.pushButton_Cancel.setText(_translate("Dialog", "Cancel", None))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>Search</p></body></html>", None))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\">Select the question file to extract the question to the database</span></p></body></html>", None))
        self.lineEdit_filelocation.setPlaceholderText(_translate("Dialog", "Select the file location", None))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p>File Location</p></body></html>", None))
        self.pushButton_browse.setText(_translate("Dialog", "Browse", None))
        self.pushButton_extract.setText(_translate("Dialog", "Extract", None))
        self.pushButton_Generate.setText(_translate("Dialog", "Process", None))

import banner_rc
