# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainingUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from GUI.canvasCreator import MplWidget
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(892, 862)
        Dialog.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 255);"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 871, 121))
        self.groupBox_4.setStyleSheet(_fromUtf8(""))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(360, 0, 61, 41))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 171, 41))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_subject = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_subject.setGeometry(QtCore.QRect(140, 10, 191, 22))
        self.comboBox_subject.setObjectName(_fromUtf8("comboBox_subject"))
        self.comboBox_Year = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_Year.setGeometry(QtCore.QRect(470, 10, 121, 22))
        self.comboBox_Year.setObjectName(_fromUtf8("comboBox_Year"))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.comboBox_Year.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(360, 40, 61, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox_Semester = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_Semester.setGeometry(QtCore.QRect(470, 50, 121, 22))
        self.comboBox_Semester.setObjectName(_fromUtf8("comboBox_Semester"))
        self.comboBox_Semester.addItem(_fromUtf8(""))
        self.comboBox_Semester.addItem(_fromUtf8(""))
        self.comboBox_Semester.addItem(_fromUtf8(""))
        self.comboBox_papertype = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_papertype.setGeometry(QtCore.QRect(140, 50, 191, 22))
        self.comboBox_papertype.setObjectName(_fromUtf8("comboBox_papertype"))
        self.comboBox_papertype.addItem(_fromUtf8(""))
        self.comboBox_papertype.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 171, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(620, 0, 61, 41))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_TotalMarks = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_TotalMarks.setGeometry(QtCore.QRect(190, 80, 141, 31))
        self.lineEdit_TotalMarks.setInputMask(_fromUtf8(""))
        self.lineEdit_TotalMarks.setObjectName(_fromUtf8("lineEdit_TotalMarks"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(18, 79, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_RemainMarks = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_RemainMarks.setGeometry(QtCore.QRect(450, 80, 141, 31))
        self.lineEdit_RemainMarks.setInputMask(_fromUtf8(""))
        self.lineEdit_RemainMarks.setObjectName(_fromUtf8("lineEdit_RemainMarks"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(358, 79, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(618, 79, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_Papermarks = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Papermarks.setGeometry(QtCore.QRect(710, 80, 141, 31))
        self.lineEdit_Papermarks.setInputMask(_fromUtf8(""))
        self.lineEdit_Papermarks.setObjectName(_fromUtf8("lineEdit_Papermarks"))
        self.comboBox_date = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_date.setGeometry(QtCore.QRect(700, 10, 151, 22))
        self.comboBox_date.setObjectName(_fromUtf8("comboBox_date"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(620, 40, 171, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_Paperno = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_Paperno.setGeometry(QtCore.QRect(710, 40, 141, 31))
        self.lineEdit_Paperno.setInputMask(_fromUtf8(""))
        self.lineEdit_Paperno.setObjectName(_fromUtf8("lineEdit_Paperno"))
        self.pushButton_Generate = QtGui.QPushButton(Dialog)
        self.pushButton_Generate.setGeometry(QtCore.QRect(750, 750, 131, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Generate.setFont(font)
        self.pushButton_Generate.setStyleSheet(_fromUtf8("QPushButton:hover{\n"
"background-color: rgb(170, 170, 127);\n"
"}"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ICONS/settings2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Generate.setIcon(icon)
        self.pushButton_Generate.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Generate.setObjectName(_fromUtf8("pushButton_Generate"))
        self.textEdit_Recomendation = QtGui.QTextEdit(Dialog)
        self.textEdit_Recomendation.setGeometry(QtCore.QRect(10, 730, 711, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.textEdit_Recomendation.setFont(font)
        self.textEdit_Recomendation.setObjectName(_fromUtf8("textEdit_Recomendation"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 680, 101, 21))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(660, 680, 101, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 410, 411, 21))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(470, 410, 411, 21))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 700, 861, 21))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 140, 871, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(40)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 430, 411, 251))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(460, 430, 411, 251))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mpl = MplWidget()
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.mpl1 = MplWidget()
        self.mpl.setObjectName(_fromUtf8("mpl1"))
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Questions Classification", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Year</p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>Subject Code</p></body></html>", None))
        self.comboBox_Year.setItemText(0, _translate("Dialog", "2015", None))
        self.comboBox_Year.setItemText(1, _translate("Dialog", "2016", None))
        self.comboBox_Year.setItemText(2, _translate("Dialog", "2017", None))
        self.comboBox_Year.setItemText(3, _translate("Dialog", "2018", None))
        self.comboBox_Year.setItemText(4, _translate("Dialog", "2019", None))
        self.comboBox_Year.setItemText(5, _translate("Dialog", "2020", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>Semester</p></body></html>", None))
        self.comboBox_Semester.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox_Semester.setItemText(1, _translate("Dialog", "2", None))
        self.comboBox_Semester.setItemText(2, _translate("Dialog", "3", None))
        self.comboBox_papertype.setItemText(0, _translate("Dialog", "Final Exam", None))
        self.comboBox_papertype.setItemText(1, _translate("Dialog", "Mid Semester", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>Question Type</p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>Date</p></body></html>", None))
        self.lineEdit_TotalMarks.setPlaceholderText(_translate("Dialog", "Enter Total Marks", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>Total Marks</p></body></html>", None))
        self.lineEdit_RemainMarks.setPlaceholderText(_translate("Dialog", "Remain Marks", None))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>Remain Marks</p></body></html>", None))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>Paper Marks</p></body></html>", None))
        self.lineEdit_Papermarks.setPlaceholderText(_translate("Dialog", "Paper Marks", None))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>Paper No</p></body></html>", None))
        self.lineEdit_Paperno.setPlaceholderText(_translate("Dialog", "Paper No", None))
        self.pushButton_Generate.setText(_translate("Dialog", "Clasify", None))
        self.textEdit_Recomendation.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None))
        self.label.setText(_translate("Dialog", "BloomsCategory", None))
        self.label_2.setText(_translate("Dialog", "BloomsCategory", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#6913ff;\">Chart-A - Percentage Expected Exam question Classification Category</span></p></body></html>", None))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#5555ff;\">Chart-B- Percentage Developed Exam question Classification Category</span></p></body></html>", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#6913ff;\">This section contains the recommendation to upgrade the paper according to the expected classification</span></p></body></html>", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "No", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Process", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Category", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Marks", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Question", None))
        self.horizontalLayout.addWidget(self.mpl)
        self.horizontalLayout_2.addWidget(self.mpl1)

import banner_rc
